import os

FRAMERATE = os.getenv('PI_GLADOS_FRAMERATE', 30)
WIDTH = os.getenv('PI_GLADOS_WIDTH', 640)
HEIGHT = os.getenv('PI_GLADOS_HEIGHT', 360)
FULLSCREEN = os.getenv('PI_GLADOS_FULLSCREEN', False)
DEFAULT_CAPTION = os.getenv('PI_GLADOS_DEFAULT_CAPTION', "piGladOS v0.1")
